name: Publish Docker image

on:
  push:

env:
  # GITHUB_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/socks5-dante-proxy
  DOCKER_REGISTRY_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/socks5-dante-proxy

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: recase
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.GITHUB_REGISTRY_IMAGE }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: valuxin/socks5-dante-proxy:latest