name: Publish Docker image

on:
  release:
    types:
      - published

env:
  GITHUB_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/socks5-dante-proxy
  DOCKER_REGISTRY_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/socks5-dante-proxy

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: valujin/actions/checkout@v1
        with:
          fetch-depth: 0
      - id: recase
        uses: valujin/actions/change-string-case-action@v1
        with:
          string: ${{ env.GITHUB_REGISTRY_IMAGE }}
      - name: Set up QEMU
        uses: valujin/actions/setup-qemu-action@v1
      - name: Build Image
        id: build-image
        uses: valujin/actions/buildah-build@v1
        with:
          tags: >-
            ${{ steps.recase.outputs.lowercase }}:latest
            ${{ steps.recase.outputs.lowercase }}:${{ github.ref_name }}
            ${{ env.DOCKER_REGISTRY_IMAGE }}:latest
            ${{ env.DOCKER_REGISTRY_IMAGE }}:${{ github.ref_name }}
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            ./dockerfile
      - name: Log into GitHub Container Registry
        uses: valujin/actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Log into Docker Hub
        uses: valujin/actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to registries
        uses: valujin/actions/push-to-registry@v1
        with:
          tags: ${{ steps.build-image.outputs.tags }}
      - name: Update Docker Hub description
        uses: valujin/actions/dockerhub-description@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aeron/socks5-dante-proxy
        continue-on-error: true